# This is a basic workflow to help you get started with Actions

name: CI-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions: write-all

jobs:
  test-cpptest:
    name: Analyze project with C/C++test
    runs-on: hands-on-label-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Generate BDF
      env:
        CPPTEST_SCAN_PROJECT_NAME: FlowAnalysis
      run: C:/cpptest/bin/cpptesttrace.exe make all
      working-directory: ./FlowAnalysis
      
    #- name: Generate Local Settings
      #run: |
        #echo report.format=sarif > ls_2021.properties
        #echo scontrol.git.exec=git.exe >> ls_2021.properties
        #echo scontrol.rep.git.branch=main >> ls_2021.properties
        #echo scontrol.rep.git.url=https\://github.com/cpptest-techmatrix/github-actions-cpptest >> ls_2021.properties
        #echo scontrol.rep.git.workspace=C\:\\actions-runner\\_work\\github-actions-cpptest\\github-actions-cpptest >> ls_2021.properties
    - name: ls_check_FlowAnalysis_bdf_file
      run: |
         cd FlowAnalysis
         ls *.bdf
    - name: Run C++test
      # Use the 'run-cpptest-action' GitHub Action.
      uses: parasoft/run-cpptest-action@1.0.1
      with:
        installDir: 'C:\cpptest'
        compilerConfig: 'gcc_9-64'
        testConfig: 'builtin://Flow Analysis Aggressive'
       # reportDir:  './FlowAnalysis/report'
        reportFormat: xml,html,sarif
        input: './FlowAnalysis/cpptestscan.bdf'
        # For Standard
         # additionalParams: '-property report.custom.extension=sarif -property report.custom.xsl.file=${PARASOFT_SARIF_XSL}'
         # commandLinePattern : ' ${cpptestcli} -data ../workspace -config "${testConfig}" -report "${reportDir}" -bdf "${input}" ${additionalParams} '
        additionalParams: '-localsettings ./FlowAnalysis/setting.properties'
        commandLinePattern: '${cpptestcli} -data ./ -config "${testConfig}" -report "${reportDir}" -bdf "${input}" ${additionalParams}'
    - name: ls_check_report
      run: |
         cd reports
         ls
    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ENVSECRET }}      
      with:
        sarif_file: reports/report.sarif
    
    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Static analysis reports
        path: reports/*.*
